version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  service-a:
    build: ./services/service_a
    container_name: service-a
    ports:
      - "8002:8001"
    depends_on:
      kafka:
        condition: service_healthy
  
  service-b:
    build: ./services/service_b
    container_name: service-b
    ports:
      - "8003:8001"
    depends_on:
      kafka:
        condition: service_healthy

  service-c:
    build: ./services/service_c
    container_name: service-c
    ports:
      - "8004:8001"
    depends_on:
      kafka:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: streamsense-postgres
    environment:
      POSTGRES_DB:        streamsense
      POSTGRES_USER:      streamsense
      POSTGRES_PASSWORD:  streamsense123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: streamsense-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: